version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URI=postgresql+psycopg2://postgres:password@db:5432/app_db
    depends_on:
      - db
      - redis
    restart: always

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: always

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    restart: always
